theme: jekyll-theme-cayman
title: Biology Capstone
description: A Collection of Summaries and Abstracts Relating to Emerging Disease Ecology 
docs_list_title: ACME Documentation
docs:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html

- title: Deployment
  url: deployment.html
